# Generated by Django 3.1.5 on 2021-01-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_integration_app', '0005_auto_20210112_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci_deploy',
            name='env1',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='c_integration_app.ci_envs'),
        ),
    ]
