# Generated by Django 3.1.5 on 2021-01-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_integration_app', '0007_remove_ci_deploy_env1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ci_deploy',
            name='env1',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='c_integration_app.ci_envs'),
            preserve_default=False,
        ),
    ]
