# Generated by Django 3.1.5 on 2021-01-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_integration_app', '0008_ci_deploy_env1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ci_deploy',
            name='env1',
        ),
    ]
